apiVersion: v1
kind: Service
metadata:
  name: scylla-manager-service
spec:
  selector:
    app: scylla-manager
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer  # Use NodePort or ClusterIP if LoadBalancer is not available.
